services:
  postgres:
    image: postgres
    container_name: postgres-notification
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: notification-service
      POSTGRES_PASSWORD: notification-service
      POSTGRES_DB: notification
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
  notification-service: # NOTE: WILL FAIL IF CERTAIN EXCHANGES / QUEUES DONT EXIST
    image: mpcs51205/notification-service:dockerTest16
    container_name: notification-service
    ports:
      - "8082:8080" # make sure LHS port unique
    command: ""
    depends_on:
      - rabbitmq
      - postgres