spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    username: notification-service
    password: notification-service
    url: jdbc:postgresql://postgres-notification:5432/notification
  rabbitmq:
    template:
      exchange-user-create: user.create
      exchange-user-delete: user.delete
      exchange-user-update: user.update
      exchange-user-activation: user.activation
      exchange-watchlist-match: watchlist.match
      exchange-auction-startsoon: auction.start-soon
      exchange-auction-endsoon: auction.end-soon
      exchange-auction-new-high-bid: auction.new-high-bid
      exchange-auction-end: auction.end
    host: rabbitmq-server
    listener:
      direct:
        retry:
          enabled: false
      fanout:
        retry:
          enabled: false